### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by ghost** [fahmiardi/laravel-mongodb-permission#2]
i am having this error when trying to install this package 
  **Problem 1
    - Installation request for fahmiardi/laravel-mongodb-permission ^0.3.0 -> satisfiable by fahmiardi/laravel-mongodb-permission[0.3].
    - fahmiardi/laravel-mongodb-permission 0.3 requires spatie/laravel-permission ~1.5.2 -> satisfiable by spatie/laravel-permission[1.5.2, 1.5.3] but these conflict with your requirements or m
inimum-stability.**

composer file : 
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravelcollective/html": "5.4.*",
        "barryvdh/laravel-elfinder": "^0.3.8",
        "magyarjeti/laravel-lipsum": "^1.1",
        "predis/predis": "~1.0",
        "intervention/image": "^2.3",
        "jenssegers/mongodb": "^3.2",
        "spatie/laravel-permission": "~2.3",
        "moloquent/moloquent": "^0.3.0"
    },

**Comment by fahmiardi** [comment]
This package doesn't support for lavarel 5.4.* because conflict with
moloquent package. When moloquent full support for laravel 5.4.*, I'll
update this package.

Thanks

**Comment by ghost** [comment]
what package should i use for this to work safely 

event though https://moloquent.github.io/master/#for-laravel-50  moloquent supports laravel >= 5.0

**Comment by fahmiardi** [comment]
I suggest you to setup your composer.json like this:

```
"require": {
"php": ">=5.6.4",
"laravel/framework": "5.3.*",
"laravelcollective/html": "5.3.*",
"barryvdh/laravel-elfinder": "^0.3.8",
"magyarjeti/laravel-lipsum": "^1.1",
"predis/predis": "~1.0",
"intervention/image": "^2.3",
"moloquent/moloquent": "^0.3.0",
"fahmiardi/laravel-mongodb-permission": "^0.3"
}
```

The main reason I use moloquent instead jenssegers/mongodb is because of I use laravel passport package. By the way, my package is still support only for laravel 5.3.*

**Comment by ghost** [comment]
that worked very well 

Thank you for your help

**Comment by fahmiardi** [comment]
You are welcome. I'll close this issue.
